### ISSUE TITLE
missing dependencies for sip-publication-client-du

### ISSUE THREAD

**Issue by samolo93** [RestComm/jain-slee#113]
Hi,
I get some errors when i started restcomm with sip ra due to dependencies of sip publication that are unable to install.
Thanks

**Comment by satanatoly** [comment]
Tested with https://github.com/RestComm/jain-slee/releases/tag/2.9.132
Sip RA and sip-publication-client-DU deployed successfully
Please note that message "Missing dependencies for sip-publication-client-DU" might appear due to sip RA has not fully deployed yet. In this case deployment of  DU is halted until dependencies are resolved
