### ISSUE TITLE
[Twiddle] Add classes for getAttribute, setAttribute and invoke methods

### ISSUE THREAD

**Issue by SergeyLee** [RestComm/jain-slee#52]
Main problem appeared with usage.service command and after my changes in AbstractOperation:

https://github.com/RestComm/jain-slee/blob/2.x/tools/twiddle/cli/src/main/java/org/mobicents/tools/twiddle/op/AbstractOperation.java#L245-L252

```
if (this.operationName.substring(0, 3).equals("set")) {
    Attribute attr = new Attribute(this.operationName.substring(3), opArguments.get(0));
    conn.setAttribute(on, attr);
} else if (this.operationName.substring(0, 3).equals("get")) {
    operationResult = conn.getAttribute(on, this.operationName.substring(3));
} else {
    operationResult = conn.invoke(on, this.operationName, parms, sig);
}
```

**Comment by jaimecasero** [comment]
A per Spec UsageMBean create an MBean operation called 
public SampleStatistics get<usage-parameter-name>(boolean reset) throws ManagementException;

This goes agaisnt general JMX Mbean convention, where get/set method names are reserved for attributes, rather than operations.

https://repository.jboss.org/nexus/content/unzip/unzip/javax/slee/jain-slee/1.1/jain-slee-1.1-javadoc.jar-unzip/index.html?javax/slee/usage/UsageMBean.html
