### ISSUE TITLE
Fix typo in SbbEntityFactoryImpl for removeSbbEntityWithCurrentClassLoader method

### ISSUE THREAD

**Issue by SergeyLee** [RestComm/jain-slee#85]
Here: https://github.com/RestComm/jain-slee/blob/2.x/container/services/src/main/java/org/mobicents/slee/runtime/sbbentity/SbbEntityFactoryImpl.java#L273-L274
I guess comment and code are inconsistent

```
// if sbb entity is not root add a tx action to ensure lock is removed
if (sbbEntityID.isRootSbbEntity()) {
```

So here I want to understand what is right: comment or code?

**Comment by jaimecasero** [comment]
it seems lock is created when "createRootSBB" is called, so that suggets there is a lock per SBB-tree, being the root SBB the owner of the lock representing the whole tree.

Under that assumption, it only makes sense to remove the lock, when the root SBB is removed. In that case, the code is right, and the comment is wrong.

wdyt?

**Comment by SergeyLee** [comment]
@jaimecasero so my conclusion: comment is wrong and you were right the root SBB the owner of the lock representing the whole tree. I fixed this comment.
Thanks for help.
